name: CI/CD Pipeline for MLFlow App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Docker
      run: |
        sudo apt-get update
        sudo apt-get install docker.io

    - name: Build Docker image
      run: |
        docker build -t my-mlflow-app .

    - name: Tag Docker image
      run: |
        docker tag my-mlflow-app mugunthragav/my-mlflow-app:latest

    - name: Push Docker image to Docker Hub
      run: |
        docker push mugunthragav/my-mlflow-app:latest

    - name: Verify Docker image
      run: |
        docker pull mugunthragav/my-mlflow-app:latest
        docker images

