name: CI/CD Pipeline for MLFlow App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:20.10.7
        options: --privileged  # Run with privileged access
        ports:
          - 2375:2375
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      run: |
        docker build -t my-mlflow-app .

    - name: Tag Docker image
      run: |
        docker tag my-mlflow-app mugunthragav/my-mlflow-app:latest

    - name: Push Docker image to Docker Hub (without login)
      run: |
        docker push mugunthragav/my-mlflow-app:latest
